# First Project: Sentiment Analysis

- Name: Nicolas Debrito
- Email: nicolas.debrito66@gmail.com
- ID Dicoding: reezzy

## Install Library

In [1]:
!pip install sastrawi
!pip install google_play_scraper

Collecting sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 3.3 MB/s eta 0:00:00
Installing collected packages: sastrawi
Successfully installed sastrawi-1.0.1
Collecting google_play_scraper
  Downloading google_play_scraper-1.2.7-py3-none-any.whl (28 kB)
Installing collected packages: google_play_scraper
Successfully installed google_play_scraper-1.2.7

## Import Library

In [2]:
import re
import string
import csv
import requests
from io import StringIO
import numpy as np
import pandas as pd
import datetime as dt
import matplotlib.pyplot as plt
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from google_play_scraper import app, reviews, Sort, reviews_all
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import pad_sequences


nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

## Scraping Data

In [3]:
scrapreview = reviews_all(
    'com.supercell.clashofclans',
    lang='id',
    country='id',
    sort=Sort.MOST_RELEVANT,
    count=10000
)

In [4]:
df = pd.DataFrame(scrapreview)
df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,6a8cccd8-5eef-4175-9468-e4af1a927fea,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"kepada pihak pengembang,tolong sesuaikan dan i...",1,695,16.253.25,2024-06-02 08:56:02,None,None,16.253.25
1,6c18b774-b23d-425e-a5e1-7e46bf972d0e,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,dari game nya sudah bagus tapi masih buruk di ...,4,688,16.253.25,2024-05-20 15:57:46,None,None,16.253.25
2,5d1028ec-66eb-4f66-8cf9-b329fa88cf61,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,COC sekarang sudah mengalami banyak sekali per...,5,5148,16.253.15,2024-04-18 15:52:30,None,None,16.253.15
3,8e45922b-b51e-47ed-bd8c-3affd2ba497f,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Jaringan data seluler bagus. Jaringan wifi bag...,1,2082,16.253.25,2024-05-16 13:25:21,None,None,16.253.25
4,9b4cb176-a5a3-41de-bb11-a2fa0fb49949,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Kenapa pas loading, banyak terjadi bug,apakah ...",2,655,16.253.25,2024-05-20 12:26:20,None,None,16.253.25

In [5]:
df.shape

(148500, 11)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148500 entries, 0 to 148499
Data columns (total 11 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   reviewId              148500 non-null  object
 1   userName              148500 non-null  object
 2   userImage             148500 non-null  object
 3   content               148500 non-null  object
 4   score                 148500 non-null  int64
 5   thumbsUpCount         148500 non-null  int64
 6   reviewCreatedVersion  107258 non-null  object
 7   at                    148500 non-null  datetime64[ns]
 8   replyContent          0 non-null       object
 9   repliedAt             0 non-null       object
 10  appVersion            107258 non-null  object
dtypes: datetime64[ns](1), int64(2), object(8)
memory usage: 12.5+ MB

In [7]:
df = df.drop_duplicates()

In [8]:
jumlah_ulasan, jumlah_kolom = df.shape
print("Jumlah Ulasan", jumlah_ulasan)
print("Jumlah Kolom", jumlah_kolom)

Jumlah Ulasan 148500
Jumlah Kolom 11

In [9]:
clean_df = df[['content']]
clean_df = clean_df.rename(columns={"content": "review"})
clean_df = clean_df.head(12000)
clean_df

                                                  review
0      kepada pihak pengembang,tolong sesuaikan dan i...
1      dari game nya sudah bagus tapi masih buruk di ...
2      COC sekarang sudah mengalami banyak sekali per...
3      Jaringan data seluler bagus. Jaringan wifi bag...
4      Kenapa pas loading, banyak terjadi bug,apakah ...
...                                                  ...
11995  Coba pengembang coc membuat sebuah token crypt...
11996  Update kali ini banyak bug. Yg di update chat ...
11997  saya suka update terbarunya , soal peningkatan...
11998  Gue pemain lama yg sempet pensi 5 tahun, sekar...
11999  game nya bagus , dari segi grafis nya juga lum...

[12000 rows x 1 columns]

## Preprocessing Data

In [10]:
def cleaningText(text):
    emoticon_pattern = re.compile(
        "["u"\U0001F600-\U0001F64F"
				u"\U0001F300-\U0001F5FF"
				u"\U0001F680-\U0001F6FF"
			  u"\U0001F1E0-\U0001F1FF"
        u"\U00002702-\U000027B0"
			  u"\U000024C2-\U0001F251"
				"]+", flags=re.UNICODE)

    text = emoticon_pattern.sub(r'', text)
    text = re.sub(r'@[A-Za-z0-9]+', '', text)
    text = re.sub(r'#[A-Za-z0-9]+', '', text)
    text = re.sub(r'RT[\s]', '', text)
    text = re.sub(r"http\S+", '', text)
    text = re.sub(r'[0-9]+', '', text)
    text = re.sub(r'[^\w\s]', '', text)

    text = text.replace('\n', ' ')
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = text.strip(' ')
    return text

def casefoldingText(text):
    text = text.lower()
    return text

slangwords = {"@": "di", "abis": "habis", "wtb": "beli", "masi": "masih", "wts": "jual", "wtt": "tukar", "bgt": "banget", "maks": "maksimal"}
def fix_slangwords(text):
    words = text.split()
    fixed_words = []

    for word in words:
        if word.lower() in slangwords:
            fixed_words.append(slangwords[word.lower()])
        else:
            fixed_words.append(word)

    fixed_text = ' '.join(fixed_words)
    return fixed_text

def tokenizingText(text):
    text = word_tokenize(text)
    return text

def filteringText(text):
    factory = StopWordRemoverFactory()
    listStopwords = set(factory.get_stop_words()) # Stopword Indonesia
    listStopwords1 = set(stopwords.words('english')) # Stopword English
    listStopwords.update(listStopwords1)
    listStopwords.update(['iya','yaa','gak','nya','na','sih','ku',"di","ga","ya","gaa","loh","kah","woi","woii","woy"])
    filtered = []
    for txt in text:
        if txt not in listStopwords:
            filtered.append(txt)
    text = filtered
    return text

def stemmingText(text):
    factory = StemmerFactory()
    stemmer = factory.create_stemmer()

    words = text.split()
    stemmed_words = [stemmer.stem(word) for word in words]
    stemmed_text = ' '.join(stemmed_words)

    return stemmed_text

def toSentence(list_words):
    sentence = ' '.join(word for word in list_words)
    return sentence

In [11]:
clean_df['text_clean'] = clean_df['review'].apply(cleaningText)
clean_df['text_casefoldingText'] = clean_df['text_clean'].apply(casefoldingText)
clean_df['text_slangwords'] = clean_df['text_casefoldingText'].apply(fix_slangwords)
clean_df['text_tokenizingText'] = clean_df['text_slangwords'].apply(tokenizingText)
clean_df['text_stopword'] = clean_df['text_tokenizingText'].apply(filteringText)
clean_df['text_akhir'] = clean_df['text_stopword'].apply(toSentence)

In [12]:
clean_df

,review,text_clean,text_casefoldingText,text_slangwords,text_tokenizingText,text_stopword,text_akhir
0,"kepada pihak pengembang,tolong sesuaikan dan i...",kepada pihak pengembangtolong sesuaikan dan im...,kepada pihak pengembangtolong sesuaikan dan im...,kepada pihak pengembangtolong sesuaikan dan im...,"[kepada, pihak, pengembangtolong, sesuaikan, d...","[pihak, pengembangtolong, sesuaikan, imbangi, ...",pihak pengembangtolong sesuaikan imbangi attac...
1,dari game nya sudah bagus tapi masih buruk di ...,dari game nya sudah bagus tapi masih buruk di ...,dari game nya sudah bagus tapi masih buruk di ...,dari game nya sudah bagus tapi masih buruk di ...,"[dari, game, nya, sudah, bagus, tapi, masih, b...","[game, bagus, buruk, bagian, koneksi, makin, k...",game bagus buruk bagian koneksi makin kesini k...
2,COC sekarang sudah mengalami banyak sekali per...,COC sekarang sudah mengalami banyak sekali per...,coc sekarang sudah mengalami banyak sekali per...,coc sekarang sudah mengalami banyak sekali per...,"[coc, sekarang, sudah, mengalami, banyak, seka...","[coc, sekarang, mengalami, banyak, sekali, per...",coc sekarang mengalami banyak sekali perkemban...
3,Jaringan data seluler bagus. Jaringan wifi bag...,Jaringan data seluler bagus Jaringan wifi bagu...,jaringan data seluler bagus jaringan wifi bagu...,jaringan data seluler bagus jaringan wifi bagu...,"[jaringan, data, seluler, bagus, jaringan, wif...","[jaringan, data, seluler, bagus, jaringan, wif...",jaringan data seluler bagus jaringan wifi bagu...
4,"Kenapa pas loading, banyak terjadi bug,apakah ...",Kenapa pas loading banyak terjadi bugapakah da...,kenapa pas loading banyak terjadi bugapakah da...,kenapa pas loading banyak terjadi bugapakah da...,"[kenapa, pas, loading, banyak, terjadi, bugapa...","[pas, loading, banyak, terjadi, bugapakah, gam...",pas loading banyak terjadi bugapakah gamenyaja...
...,...,...,...,...,...,...,...
11995,Coba pengembang coc membuat sebuah token crypt...,Coba pengembang coc membuat sebuah token crypt...,coba pengembang coc membuat sebuah token crypt...,coba pengembang coc membuat sebuah token crypt...,"[coba, pengembang, coc, membuat, sebuah, token...","[coba, pengembang, coc, membuat, sebuah, token...",coba pengembang coc membuat sebuah token crypt...
11996,Update kali ini banyak bug. Yg di update chat ...,Update kali ini banyak bug Yg di update chat d...,update kali ini banyak bug yg di update chat d...,update kali ini banyak bug yg di update chat d...,"[update, kali, ini, banyak, bug, yg, di, updat...","[update, kali, banyak, bug, yg, update, chat, ...",update kali banyak bug yg update chat dong jelas
11997,"saya suka update terbarunya , soal peningkatan...",saya suka update terbarunya soal peningkatan ...,saya suka update terbarunya soal peningkatan ...,saya suka update terbarunya soal peningkatan u...,"[saya, suka, update, terbarunya, soal, peningk...","[suka, update, terbarunya, soal, peningkatan, ...",suka update terbarunya soal peningkatan udah p...
11998,"Gue pemain lama yg sempet pensi 5 tahun, sekar...",Gue pemain lama yg sempet pensi tahun sekaran...,gue pemain lama yg sempet pensi tahun sekaran...,gue pemain lama yg sempet pensi tahun sekarang...,"[gue, pemain, lama, yg, sempet, pensi, tahun, ...","[gue, pemain, lama, yg, sempet, pensi, tahun, ...",gue pemain lama yg sempet pensi tahun sekarang...
11999,"game nya bagus , dari segi grafis nya juga lum...",game nya bagus dari segi grafis nya juga luma...,game nya bagus dari segi grafis nya juga luma...,game nya bagus dari segi grafis nya juga lumay...,"[game, nya, bagus, dari, segi, grafis, nya, ju...","[game, bagus, segi, grafis, lumayan, jadi, per...",game bagus segi grafis lumayan jadi permasalah...

## Labeling Data

In [13]:
clean_df = clean_df.dropna()
print("Jumlah Ulasan", clean_df.shape[0])

Jumlah Ulasan 12000

In [14]:
lexicon_positive = dict()

response = requests.get('https://raw.githubusercontent.com/angelmetanosaa/dataset/main/lexicon_positive.csv')

if response.status_code == 200:
    reader = csv.reader(StringIO(response.text), delimiter=',')
    for row in reader:
        lexicon_positive[row[0]] = int(row[1])
else:
    print("Failed to fetch positive lexicon data")

lexicon_negative = dict()

response = requests.get('https://raw.githubusercontent.com/angelmetanosaa/dataset/main/lexicon_negative.csv')

if response.status_code == 200:
    reader = csv.reader(StringIO(response.text), delimiter=',')
    for row in reader:
        lexicon_negative[row[0]] = int(row[1])
else:
    print("Failed to fetch negative lexicon data")

In [15]:
def sentiment_analysis_lexicon_indonesia(text):
    score = 0
    for word in text.split():
        if (word in lexicon_positive):
            score = score + lexicon_positive[word]

    for word in text.split():
        if (word in lexicon_negative):
            score = score + lexicon_negative[word]

    polarity=''

    if (score > 0):
        polarity = 'positive'
    elif (score < 0):
        polarity = 'negative'
    else:
        polarity = 'neutral'

    return score, polarity

In [16]:
results = clean_df['text_akhir'].apply(sentiment_analysis_lexicon_indonesia)
results = list(zip(*results))
clean_df['sentimen_score'] = results[0]
clean_df['sentimen'] = results[1]
print(clean_df['sentimen'].value_counts())

sentimen
negative    7779
positive    3560
neutral      661
Name: count, dtype: int64

In [17]:
clean_df.to_csv('labeling_data.csv', index=False)